### ISSUE TITLE
Error getting module source

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/extension-builder#5]
When trying this out on ipywidgets, I'm getting this error:

```
TypeError: dependencyTemplates.get is not a function
    at doDep (/[path]/ipywidgets/labextension/node_modules/webpack/lib/NormalModule.js:136:38)
    at Array.forEach (native)
    at doBlock (/[path]/ipywidgets/labextension/node_modules/webpack/lib/NormalModule.js:151:22)
    at DependenciesBlock.NormalModule.source (/[path]/ipywidgets/labextension/node_modules/webpack/lib/NormalModule.js:186:2)
    at JupyterLabPlugin._parseModule (/[path]/ipywidgets/labextension/node_modules/jupyterlab-extension-builder/lib/plugin.js:115:26)
    at /[path]/ipywidgets/labextension/node_modules/jupyterlab-extension-builder/lib/plugin.js:54:36
    at Array.forEach (native)
    at /[path]/ipywidgets/labextension/node_modules/jupyterlab-extension-builder/lib/plugin.js:48:27
    at Array.forEach (native)
    at JupyterLabPlugin._onEmit (/[path]/ipywidgets/labextension/node_modules/jupyterlab-extension-builder/lib/plugin.js:43:28)
```

In debugging this, I see that line https://github.com/jupyter/jupyterlab-extension-builder/blob/master/src/plugin.ts#L137 has a call `source()`, but that function in webpack, https://github.com/webpack/webpack/blob/v1.13.2/lib/NormalModule.js#L119, requires some arguments that get used when there are dependencies.

This is using https://github.com/ipython/ipywidgets/pull/727 (cloned to be sibling of the jupyterlab repo, and then running `npm run build` in the `ipywidgets/labextension` directory.

**Comment by jasongrout** [comment]
Changing the javascript of https://github.com/jupyter/jupyterlab-extension-builder/blob/master/src/plugin.ts#L137 to `mod._source.source()` gets rid of the error, but there still seems to be something wrong with the generated bundle - the requires don't use the jupyter require and aren't mangled. I'll keep digging...

**Comment by jasongrout** [comment]
Very weird, but I tried from a clean slate, and things seemed to work fine. Closing.

**Comment by blink1073** [comment]
I think this is a matter of whether the cached source was available in that function or not.  We can either call the private _source() or provide the proper arguments to source().  The first two are attributes of the compilation.
